version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: olx-nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./app:/var/www
    depends_on:
      - app
    networks:
      - olx-network

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: olx-app
    volumes:
      - ./app:/var/www
    expose:
      - "9000"
    networks:
      - olx-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: olx-db
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "olx_tracker"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - olx-network

  olx-cron:
    image: alpine
    container_name: olx-cron
    volumes:
      - ./refresh_prices.sh:/refresh_prices.sh
    entrypoint: >
      /bin/sh -c "crontab -l | { cat; echo '*/15 * * * * /refresh_prices.sh > /proc/1/fd/1 2>/proc/1/fd/2'; } | crontab -
      && crond -f"

volumes:
  db-data:

networks:
  olx-network:
    driver: bridge