version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    platform: linux/amd64,linux/arm64
    container_name: olx-app
    volumes:
      - ./app:/var/www
    ports:
      - "9000:9000"
    networks:
      - olx-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    platform: linux/amd64,linux/arm64
    container_name: olx-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: olx_tracker
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - olx-network

volumes:
  db-data:

networks:
  olx-network:
    driver: bridge